fix: dir is not working

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -16,8 +16,8 @@ jobs:
 
       - name: Run Build
         run: |
-          npm run build >> /home/ubuntu/library-api/deploy.log 2>&1 || {
-            echo "Build failed at $(date)" >> /home/ubuntu/library-api/deploy.log
+          npm run build >> ./library-api/deploy.log 2>&1 || {
+            echo "Build failed at $(date)" >> ./library-api/deploy.log
             exit 1
           }
 
